; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.44"

; Modules

projects[views_bulk_operations][version] = "3.3"
projects[admin_menu][version] = "3.0-rc5"
projects[admin_views][version] = "1.5"
projects[ctools][version] = "1.9"
projects[date][version] = "2.9"
projects[devel][version] = "1.5"
projects[entity][version] = "1.7"
projects[entityreference][version] = "1.1"
projects[features][version] = "2.10"
projects[module_filter][version] = "2.0"
projects[querypath][version] = "2.1"
projects[views][version] = "3.13"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dll_cat][download][type] = "git"
projects[dll_cat][type] = "module"
projects[dll_cat][download][url] = "https://github.com/OULibraries/dll_cat.git"






